services:

  mysql-sisdb:
    image: mysql:8.0
    container_name: mysql-sisdb
    restart: always
    environment:
      MYSQL_DATABASE: sisdb2025
      MYSQL_ROOT_PASSWORD: abcd
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - libros-net

  autores:
    build: ./Autor-ms_Distri
    container_name: autores
    ports:
      - "8002:8002"
    environment:
      DB_HOST: mysql-sisdb
      DB_PORT: 3306
      DB_NAME: sisdb2025
      DB_USER: root
      DB_PWD: abcd
    depends_on:
      - mysql-sisdb
    networks:
      - libros-net

  libros:
    build: ./test
    container_name: libros
    ports:
      - "8001:8001"
    environment:
      DB_HOST: mysql-sisdb
      DB_PORT: 3306
      DB_NAME: sisdb2025
      DB_USER: root
      DB_PWD: abcd
    depends_on:
      - mysql-sisdb
      - autores
    networks:
      - libros-net

volumes:
  mysql_data:

networks:
  libros-net:
    driver: bridge
